from __future__ import annotations
from datetime import date
from pathlib import Path
from typing import TYPE_CHECKING
from jinja2 import Environment, BaseLoader
from agent.utils.logger import get_logger

if TYPE_CHECKING:
    from agent.services.memory_service import MemoryEntry

log = get_logger(__name__)

REPORT_TEMPLATE = """\
# .NET MAUI Crash Report — {{ report_date }}

**Period:** Last 7 days | **Generated by:** maui-crash-agent

---

## Executive Summary

| Metric | Value |
|--------|-------|
| Total crashes analyzed | {{ stats.total }} |
| New crashes | {{ stats.new }} |
| Recurring crashes | {{ stats.recurring }} |
| Regressions | {{ stats.regressions }} |
| Jira tickets created | {{ stats.tickets }} |
| PRs raised | {{ stats.prs }} |
| P0 (Critical) | {{ stats.p0 }} |
| P1 (High) | {{ stats.p1 }} |

---

{% for priority in ['P0', 'P1', 'P2', 'P3'] %}
{% set group = crashes | selectattr('priority', 'equalto', priority) | list %}
{% if group %}
## {{ priority_labels[priority] }}

{% for crash in group %}
### [{{ crash.jira_ticket or 'PENDING' }}] {{ crash.crash_name or crash.exception_type }}

**Score:** {{ crash.severity_score }}/100 | **Pattern:** {{ crash.pattern }} | **Platform:** {{ crash.platform }}
**Occurrences:** {{ crash.occurrence_count }} | **Status:** {{ crash.status }}
{% if crash.pr_url %}**PR:** [{{ crash.pr_branch }}]({{ crash.pr_url }}){% endif %}

**Root Cause:** {{ crash.root_cause }}

**Fix:** {{ crash.fix }}

---
{% endfor %}
{% endif %}
{% endfor %}

## Top Patterns

{% for pattern, count in top_patterns %}
- `{{ pattern }}`: {{ count }} crash(es)
{% endfor %}

---
*Generated by maui-crash-agent on {{ report_date }}*
"""

PRIORITY_LABELS = {"P0": "🔴 P0 — Critical (fix today)", "P1": "🟠 P1 — High (fix this sprint)", "P2": "🟡 P2 — Medium (fix next sprint)", "P3": "⚪ P3 — Low (backlog)"}


class ReportService:
    def __init__(self, reports_dir: Path) -> None:
        self._dir = reports_dir
        self._env = Environment(loader=BaseLoader())

    async def generate(self, crashes: list, report_date: date) -> Path:
        stats = {"total": len(crashes), "new": sum(1 for c in crashes if c.recurrence_count == 1), "recurring": sum(1 for c in crashes if c.recurrence_count > 1), "regressions": sum(1 for c in crashes if c.status == "regression"), "tickets": sum(1 for c in crashes if c.jira_ticket), "prs": sum(1 for c in crashes if c.pr_url), "p0": sum(1 for c in crashes if c.priority == "P0"), "p1": sum(1 for c in crashes if c.priority == "P1")}
        counts: dict = {}
        for c in crashes:
            counts[c.pattern] = counts.get(c.pattern, 0) + 1
        top_patterns = sorted(counts.items(), key=lambda x: x[1], reverse=True)[:5]
        content = self._env.from_string(REPORT_TEMPLATE).render(report_date=report_date.isoformat(), crashes=crashes, stats=stats, top_patterns=top_patterns, priority_labels=PRIORITY_LABELS)
        path = self._dir / f"crash-report-{report_date.isoformat()}.md"
        path.write_text(content, encoding="utf-8")
        return path
