from __future__ import annotations
import re, subprocess
from pathlib import Path
from typing import TYPE_CHECKING
from agent.utils.logger import get_logger

if TYPE_CHECKING:
    from agent.core.executor import PhaseExecutor

log = get_logger(__name__)


async def run(executor: "PhaseExecutor") -> None:
    project_root = executor.state.get("project_root", Path("."))
    for item in executor.state.get("analyses", []):
        if not item.get("fixed_files") or not item.get("build_passed"):
            continue
        analysis, crash = item.get("analysis"), item["crash"]
        jira_ticket = item.get("jira_ticket", "UNKNOWN")
        pattern = getattr(analysis, "pattern", "crash") if analysis else "crash"
        branch_name = f"fix/{jira_ticket.lower()}-{re.sub(r'[^a-z0-9-]', '-', pattern.lower())[:30]}"
        pr_title = f"[{jira_ticket}] fix: {crash.exception_type.split('.')[-1]} — {crash.platform.capitalize()} ({getattr(analysis, 'priority', 'P?') if analysis else 'P?'})"
        review_block = ("\n\n## ⚠️ Review Flags\n" + "\n".join(f"- {f}" for f in item.get("review_failed", []))) if item.get("review_failed") else ""
        pr_body = f"""## Summary\nFixes a crash affecting **{crash.affected_users} users** ({crash.occurrence_count} occurrences).\n\n## Jira\n[{jira_ticket}]({item.get('jira_url', '')})\n\n## Root Cause\n{getattr(analysis, 'root_cause', 'See Jira.') if analysis else 'See Jira.'}\n\n## Fix\n{getattr(analysis, 'fix_summary', 'See changed files.') if analysis else 'See changed files.'}\n\n## Testing\n- [ ] Tested on Android\n- [ ] Tested on iOS\n- [ ] dotnet build passes{review_block}\n\n---\n*Auto-generated by maui-crash-agent*"""
        try:
            await executor.github.create_branch(branch_name)
            for f in item["fixed_files"]:
                fp = project_root / f
                await executor.github.push_file(branch=branch_name, file_path=f, content=fp.read_text(encoding="utf-8"), commit_message=f"fix: {crash.exception_type.split('.')[-1]} in {f.split('/')[-1]}\n\nFixes {jira_ticket}")
            pr = await executor.github.create_pr(title=pr_title, body=pr_body, head_branch=branch_name)
            item["pr_url"] = pr["url"]
            item["pr_branch"] = branch_name
            executor.results["prs_raised"] += 1
            log.info("Raised PR #%d: %s", pr["number"], pr["url"])
        except Exception as e:
            log.error("PR failed for %s: %s", item["signature"], e)
